# 建库
CREATE DATABASE `guigu-oa`;
USE `guigu-oa`;

# 角色表
CREATE TABLE `sys_role`(
`id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '角色ID',
`role_name` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '角色名称',
`role_code` VARCHAR(20) DEFAULT NULL COMMENT '角色编码',
`description` VARCHAR(255) DEFAULT NULL COMMENT '描述',
`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记（0：不可用 1：可用）'
) COMMENT '角色表';

# 用户表
CREATE TABLE `sys_user`(
`id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '会员id',
`username` VARCHAR(20) NOT NULL DEFAULT '' UNIQUE COMMENT '用户名',
`password` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '密码',
`name` VARCHAR(50) DEFAULT NULL COMMENT '姓名',
`phone` VARCHAR(11) DEFAULT NULL COMMENT '手机',
`head_url` VARCHAR(200) DEFAULT NULL COMMENT '头像地址',
`dept_id` BIGINT DEFAULT NULL COMMENT '部门id',
`post_id` BIGINT DEFAULT NULL COMMENT '岗位id',
`open_id` VARCHAR(255) DEFAULT NULL COMMENT '微信openId',
`description` VARCHAR(255) DEFAULT NULL COMMENT '描述',
`status` TINYINT DEFAULT NULL COMMENT '状态（1：正常 0：停用）',
`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记（0：不可用 1：可用）'
) COMMENT '用户表';

# 角色-用户 关系表
CREATE TABLE `sys_user_role`(
`id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键id',
`role_id` BIGINT NOT NULL DEFAULT 0 COMMENT '角色id',
`user_id` BIGINT NOT NULL DEFAULT 0 COMMENT '用户id',
`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
`is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记（0：不可用 1：可用）'
) COMMENT '用户-角色';

# 菜单表
CREATE TABLE `sys_menu`(
`id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '编号',
`parent_id` BIGINT NOT NULL DEFAULT 0 COMMENT '所属上级',
`name` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '名称',
`type` TINYINT NOT NULL DEFAULT 0 COMMENT '类型（0：目录 1：菜单 2：按钮）',
`path` VARCHAR(100) DEFAULT NULL COMMENT '路由地址',
`component` VARCHAR(100) DEFAULT NULL COMMENT '组件地址',
`perms` VARCHAR(100) DEFAULT NULL COMMENT '权限标识',
`icon` VARCHAR(100) DEFAULT NULL COMMENT '图标',
`sort_value` INT DEFAULT NULL COMMENT '排序',
`status` TINYINT DEFAULT NULL COMMENT '状态（0：禁止 1：正常）',
`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记（0：不可用 1：可用）'
) COMMENT '菜单表';

# 角色-菜单 关系表
CREATE TABLE `sys_role_menu`(
`id` BIGINT PRIMARY KEY AUTO_INCREMENT,
`role_id` BIGINT NOT NULL DEFAULT 0,
`menu_id` BIGINT NOT NULL DEFAULT 0,
`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记（0：不可用 1：可用）'
) COMMENT '角色-菜单';

# 审批模板类型表
CREATE TABLE `oa_process_type`(
`id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'id',
`name` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '类型名称',
`description` VARCHAR(255) DEFAULT NULL COMMENT '描述',
`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记（0：不可用 1：可用）'
) COMMENT '审批模板类型';

# 审批模板表
CREATE TABLE `oa_process_template`(
`id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '角色id',
`name` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '模板名称',
`icon_url` VARCHAR(100) COMMENT '图标路径',
`process_type_id` BIGINT DEFAULT 0,
`form_props` TEXT COMMENT '表单属性',
`form_options` TEXT COMMENT '表单选项',
`process_definition_key` VARCHAR(20) COMMENT '流程定义key',
`process_definition_path` VARCHAR(255) COMMENT '流程定义上传路径',
`process_model_id` VARCHAR(255) COMMENT '流程定义模板id',
`description` VARCHAR(255) COMMENT '描述',
`status` TINYINT NOT NULL DEFAULT 0,
`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记（0：不可用 1：可用）'
) COMMENT '审批模板';

# 审批信息表
CREATE TABLE `oa_process`(
`id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'id',
`process_code` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '审批code',
`user_id` BIGINT NOT NULL DEFAULT 0 COMMENT '用户id',
`process_template_id` BIGINT DEFAULT NULL COMMENT '审批模板id',
`process_type_id` BIGINT DEFAULT NULL COMMENT '审批类型id',
`title` VARCHAR(255) COMMENT '标题',
`description` VARCHAR(255) COMMENT '描述',
`form_values` TEXT COMMENT '表单值',
`process_instance_id` VARCHAR(255) COMMENT '流程实例id',
`current_auditor` VARCHAR(255) COMMENT '当前审批人',
`status` TINYINT COMMENT '状态（0：默认 1：审批中 2：审批通过 -1：驳回）',
`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记（0：不可用 1：可用）'
) COMMENT '审批类型';

# 审批记录表
CREATE TABLE `oa_process_record`(
`id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'id',
`process_id` BIGINT NOT NULL DEFAULT 0 COMMENT '审批流程id',
`description` VARCHAR(255) COMMENT '审批描述',
`status` TINYINT DEFAULT 0 COMMENT '状态',
`operate_user_id` BIGINT DEFAULT 0 COMMENT '操作用户id',
`operate_user` VARCHAR(20) COMMENT '操作用户',
`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '删除标记（0：不可用 1：可用）'
) COMMENT '审批记录';

# 微信公众号菜单表
CREATE TABLE `wechat_menu`(
`id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '编号',
`parent_id` BIGINT COMMENT '上级id',
`name` VARCHAR(50) COMMENT '菜单名称',
`type` VARCHAR(10) COMMENT '类型',
`url` VARCHAR(100) COMMENT '网页链接（用户点击菜单可打开链接）',
`menu_key` VARCHAR(20) COMMENT '菜单key值（用于消息接口推送）',
`sort` TINYINT COMMENT '排序',
`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`is_deleted` TINYINT DEFAULT 0
) COMMENT '公众号菜单'